Blinds02/Models/OrderItem.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Blinds02.Models
{
    public class OrderItem
    {
        public int OrderItemID { get; set; }

        public int OrderID { get; set; }
        public virtual Order Order { get; set; }

        public int BlindItemID { get; set; }
        public virtual BlindItem BlindItem { get; set; }

        public int Quantity { get; set; }

        [DisplayFormat(DataFormatString = "{0:0.00 zł}")]
        public double Price { get; set; }

        public void UpdatePrice(BlindItem blindItem)
        {
            this.Price = Math.Round(blindItem.Price * this.Quantity, 2);
        }
    }
}

Blinds02/Controllers/BlindItemsController.cs
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Blinds02.Models;

namespace Blinds02.Controllers
{
    public class BlindItemsController : Controller
    {
        private Blinds02Context db = new Blinds02Context();

        // GET: BlindItems
        public ActionResult Index()
        {
            var blindItems = db.BlindItems.Include(b => b.Textile);
            var last20BlindItems = (from item in blindItems
                                    where item.BlindItemID > (blindItems.Count() - 20)
                                    orderby item.BlindItemID descending
                                    select item);
            return View(last20BlindItems.ToList());
        }

        // GET: BlindItems/Details
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlindItem blindItem = db.BlindItems.Find(id);

            if (blindItem == null)
            {
                return HttpNotFound();
            }
            return View(blindItem);
        }

        // GET: BlindItems/Create
        public ActionResult Create()
        {
            ViewBag.TextileID = new SelectList(db.Textiles, "TextileID", "TextileName");
            return View();
        }

        // POST: BlindItems/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BlindItemID,Width,Height,TextileID")] BlindItem blindItem)
        {
            Textile textile = db.Textiles.Find(blindItem.TextileID);

            blindItem.UpdateItem(textile);

            if (ModelState.IsValid)
            {
                db.BlindItems.Add(blindItem);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.TextileID = new SelectList(db.Textiles, "TextileID", "TextileName", blindItem.TextileID);
            return View(blindItem);
        }

        // GET: BlindItems/Edit
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlindItem blindItem = db.BlindItems.Find(id);
            if (blindItem == null)
            {
                return HttpNotFound();
            }
            ViewBag.TextileID = new SelectList(db.Textiles, "TextileID", "TextileName", blindItem.TextileID);
            return View(blindItem);
        }

        // POST: BlindItems/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BlindItemID,Width,Height,TextileID")] BlindItem blindItem)
        {
            Textile textile = db.Textiles.Find(blindItem.TextileID);

            blindItem.UpdateItem(textile);
            if (ModelState.IsValid)
            {
                db.Entry(blindItem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TextileID = new SelectList(db.Textiles, "TextileID", "TextileName", blindItem.TextileID);
            return View(blindItem);
        }

        // GET: BlindItems/Delete
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (db.OrderItems.Where(o => o.BlindItemID == id).Count() > 0)
            {
                return RedirectToAction("Warning", "Warning", new Warning()
                { WarningText = "You can't delete this Blind - it is included in orders." });
            }
            BlindItem blindItem = db.BlindItems.Find(id);
            if (blindItem == null)
            {
                return HttpNotFound();
            }
            return View(blindItem);
        }

        // POST: BlindItems/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BlindItem blindItem = db.BlindItems.Find(id);
            db.BlindItems.Remove(blindItem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Blinds02/Controllers/OrderItemsController.cs
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Blinds02.Models;

namespace Blinds02.Controllers
{
    public class OrderItemsController : Controller
    {
        private Blinds02Context db = new Blinds02Context();

        // GET: OrderItems
        public ActionResult Index(int? orderID)
        {
            if (orderID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                var orderItems = db.OrderItems.Include(o => o.BlindItem).Include(o => o.Order).
                    Where(o => o.OrderID == orderID);
                if (orderItems.Count() > 0)
                {
                    return View(orderItems.ToList());
                }
                return RedirectToAction("Details", "Orders", new { id = orderID });
            }
        }

        // GET: OrderItems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderItem orderItem = db.OrderItems.Find(id);
            if (orderItem == null)
            {
                return HttpNotFound();
            }
            return View(orderItem);
        }

        // GET: OrderItems/Create
        public ActionResult Create(int? blindItemID, int? orderID)
        {
            Order order = db.Orders.Find(orderID);
            BlindItem blindItem = db.BlindItems.Find(blindItemID);
            if (blindItem == null && order == null)
            {
                ViewBag.BlindItemID = new SelectList(db.BlindItems, "BlindItemID", "Name");
                ViewBag.OrderID = new SelectList(db.Orders, "OrderID", "OrderID");
                return View();
            }
            else
            {
                OrderItem orderItem = new OrderItem();
                if (order != null)
                {
                    orderItem.OrderID = order.OrderID;
                }
                if (blindItem != null)
                {
                    orderItem.BlindItemID = blindItem.BlindItemID;
                }
                ViewBag.BlindItemID = new SelectList(db.BlindItems, "BlindItemID", "Name");
                ViewBag.OrderID = new SelectList(db.Orders, "OrderID", "OrderID");
                return View(orderItem);
            }
        }

        // POST: OrderItems/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OrderItemID,OrderID,BlindItemID,Quantity")] OrderItem orderItem)
        {
            BlindItem blindItem = db.BlindItems.Find(orderItem.BlindItemID);
            orderItem.UpdatePrice(blindItem);
            if (ModelState.IsValid)
            {
                db.OrderItems.Add(orderItem);
                db.SaveChanges();
                return RedirectToAction("UpdateOrder", new { id = orderItem.OrderID });
            }

            ViewBag.BlindItemID = new SelectList(db.BlindItems, "BlindItemID", "Name", orderItem.BlindItemID);
            ViewBag.OrderID = new SelectList(db.Orders, "OrderID", "OrderID", orderItem.OrderID);
            return View(orderItem);
        }

        // GET: OrderItems/Edit
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderItem orderItem = db.OrderItems.Find(id);
            if (orderItem == null)
            {
                return HttpNotFound();
            }
            ViewBag.BlindItemID = new SelectList(db.BlindItems, "BlindItemID", "Name", orderItem.BlindItemID);
            ViewBag.OrderID = new SelectList(db.Orders, "OrderID", "OrderID", orderItem.OrderID);
            return View(orderItem);
        }

        // POST: OrderItems/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OrderItemID,OrderID,BlindItemID,Quantity")] OrderItem orderItem)
        {
            BlindItem blindItem = db.BlindItems.Find(orderItem.BlindItemID);
            orderItem.UpdatePrice(blindItem);
            if (ModelState.IsValid)
            {
                db.Entry(orderItem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("UpdateOrder", new { id = orderItem.OrderID });
            }
            ViewBag.BlindItemID = new SelectList(db.BlindItems, "BlindItemID", "Name", orderItem.BlindItemID);
            ViewBag.OrderID = new SelectList(db.Orders, "OrderID", "OrderID", orderItem.OrderID);
            return View(orderItem);
        }

        // GET: OrderItems/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderItem orderItem = db.OrderItems.Find(id);
            if (orderItem == null)
            {
                return HttpNotFound();
            }
            return View(orderItem);
        }

        // POST: OrderItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            OrderItem orderItem = db.OrderItems.Find(id);
            db.OrderItems.Remove(orderItem);
            db.SaveChanges();
            return RedirectToAction("Index", new { orderID = orderItem.OrderID });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult UpdateOrder(int id)
        {
            Order order = db.Orders.Find(id);
            order.UpdateOrderValue();

            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { orderID = order.OrderID });
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }
    }
}

Blinds02/Views/OrderItems/Create.cshtml
@model Blinds02.Models.OrderItem

@{
    ViewBag.Title = "Create";
}

<h2>Create Order Item</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>OrderItem</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.OrderID, "OrderID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("OrderID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OrderID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BlindItemID, "BlindItemID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BlindItemID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BlindItemID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<p>
    @Html.ActionLink("List of Blinds", "Index", "BlindItems") |
    @Html.ActionLink("Add new Blind", "Create", "BlindItems") |
    @Html.ActionLink("List of Order Items", "Index", "OrderItems", new { orderID = Model.OrderID }, Model) |
    @Html.ActionLink("Order Details", "Details", "Orders", new { id = Model.OrderID }, Model) |
    @Html.ActionLink("Create new Order", "Create", "Orders")
</p>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Blinds02/Views/OrderItems/Delete.cshtml
@model Blinds02.Models.OrderItem

@{
    ViewBag.Title = "Delete";
}

<h2>Delete Order Item</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OrderItem</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BlindItem.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BlindItem.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Order.OrderID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Order.OrderID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Blinds02/Views/OrderItems/Details.cshtml
@model Blinds02.Models.OrderItem

@{
    ViewBag.Title = "Details";
}

<h2>Order Item Details</h2>

<div>
    <h4>OrderItem</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BlindItem.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BlindItem.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Order.OrderID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Order.OrderID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.OrderItemID }) |
    @Html.ActionLink("List of Order Items", "Index", "OrderItems", new { orderID = Model.OrderID }, Model) |
    @Html.ActionLink("Order Details", "Details", "Orders", new { id = Model.OrderID }, Model) |
</p>

Blinds02/Views/OrderItems/Edit.cshtml
@model Blinds02.Models.OrderItem

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Order Item</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>OrderItem</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.OrderItemID)

        <div class="form-group">
            @Html.LabelFor(model => model.OrderID, "OrderID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("OrderID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OrderID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BlindItemID, "BlindItemID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BlindItemID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BlindItemID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { orderID = Model.OrderID })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Blinds02/Views/OrderItems/Index.cshtml
@model IEnumerable<Blinds02.Models.OrderItem>

@{
    ViewBag.Title = "Order List";
}

<h2>Order Items List</h2>

<p>
    @Html.ActionLink("Create New", "Create", new { orderID = Model.First().OrderID })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BlindItem.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Order.OrderID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th></th>
    </tr>
    @{
        double sum = 0;
        foreach (var item in Model)
        {
            sum += item.Price;
        }
    }
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BlindItem.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Order.OrderID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.OrderItemID }) |
                @Html.ActionLink("Details", "Details", new { id = item.OrderItemID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.OrderItemID })
            </td>
        </tr>
    }

</table>
@{
    if (Model.Count() > 0)
    {
        <p>
            Total for order no
            @Html.DisplayFor(item => Model.First().OrderID)
            :
            @Html.DisplayFor(item => Model.First().Order.OrderValue)
        </p>
        <p>
            @Html.ActionLink("Order Details", "Details", "Orders", new { id = Model.First().OrderID }, Model)
        </p>
    }
}